@testset "DrawDrift" begin

dmtx = Int8[ 8 8 8 ; 8 0 8 ; 8 8 1 ]; d = Drift(dmtx)

ltx = draw_drift(d, mode=:ps)

@test ltx == "%% Auto-generated by draw_drift\n\\psset{unit=0.7cm,linewidth=0.8pt}\n\\begin{pspicture}(0,0)(3,3)\n\\psline[linecolor=lightgray] (0,1)(3,1)\n\\psline[linecolor=lightgray] (0,2)(3,2)\n\\psline[linecolor=lightgray] (1,0)(1,3)\n\\psline[linecolor=lightgray] (2,0)(2,3)\n\\psline[linecolor=gray](0,0)(3,0)(3,3)(0,3)(0,0)\n\\psframe*[linecolor=orange!30] (1.00,1.00)(2.00,2.00)\n\\psline[linecolor=orange] (1.00,1.00)(2.00,1.00)(2.00,2.00)(1.00,2.00)(1.00,1.00)\n\\psline[linecolor=blue] (2.50,0.00)(2.50,1.00)\n\\psline[linecolor=blue] (2.00,0.50)(3.00,0.50)\n\\end{pspicture}\n"

end
